# Generated by Django 3.1.1 on 2020-09-22 19:29

import django.core.validators
from django.db import migrations, models
import handset.validators
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNo', models.IntegerField()),
                ('Password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('confirmPassword', models.CharField(max_length=100)),
                ('MacAddress', models.CharField(default='aa:bb:cc:dd:ee:ff', max_length=20, validators=[handset.validators.validate_MAC])),
                ('ManagerName', models.CharField(max_length=100)),
                ('ManagerPhoneNo', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('Department', models.CharField(max_length=100)),
                ('FinalApprover', models.CharField(max_length=100, verbose_name='Final Approver')),
            ],
        ),
    ]
