# Generated by Django 3.1.1 on 2020-09-23 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handset',
            name='Password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
